import type { CharacterConfig, FactionTemplate, RegionConfig } from './types';

export const regions: RegionConfig[] = [
  {
    id: 'liaodong',
    name: '辽东',
    neighbors: ['mobei', 'hebei', 'shandong'],
    center: { x: 760, y: 180 },
    polygon: [],
    provinceNames: ['辽宁', '吉林', '黑龙江'],
  },
  {
    id: 'mobei',
    name: '漠北',
    neighbors: ['liaodong', 'hebei', 'xiliang'],
    center: { x: 430, y: 92 },
    polygon: [],
    provinceNames: ['新疆', '内蒙古', '青海', '甘肃', '宁夏'],
  },
  {
    id: 'xiliang',
    name: '西凉',
    neighbors: ['mobei', 'guanzhong', 'bashu'],
    center: { x: 196, y: 236 },
    polygon: [],
    provinceNames: ['陕西', '山西'],
  },
  {
    id: 'hebei',
    name: '河北',
    neighbors: ['liaodong', 'mobei', 'xiliang', 'zhongyuan', 'shandong'],
    center: { x: 598, y: 260 },
    polygon: [],
    provinceNames: ['河北', '北京', '天津'],
  },
  {
    id: 'guanzhong',
    name: '关中',
    neighbors: ['xiliang', 'zhongyuan', 'bashu', 'jingchu', 'hebei'],
    center: { x: 432, y: 315 },
    polygon: [],
    provinceNames: ['河南'],
  },
  {
    id: 'shandong',
    name: '山东',
    neighbors: ['liaodong', 'hebei', 'zhongyuan', 'jiangdong'],
    center: { x: 712, y: 336 },
    polygon: [],
    provinceNames: ['山东'],
  },
  {
    id: 'zhongyuan',
    name: '中原',
    neighbors: ['hebei', 'guanzhong', 'shandong', 'jingchu', 'jiangdong'],
    center: { x: 546, y: 404 },
    polygon: [],
    provinceNames: ['安徽', '湖北'],
  },
  {
    id: 'bashu',
    name: '巴蜀',
    neighbors: ['xiliang', 'guanzhong', 'jingchu', 'lingnan'],
    center: { x: 260, y: 470 },
    polygon: [],
    provinceNames: ['四川', '重庆', '西藏'],
  },
  {
    id: 'jingchu',
    name: '荆楚',
    neighbors: ['guanzhong', 'zhongyuan', 'bashu', 'jiangdong', 'lingnan'],
    center: { x: 516, y: 542 },
    polygon: [],
    provinceNames: ['湖南', '江西', '贵州'],
  },
  {
    id: 'jiangdong',
    name: '江东',
    neighbors: ['shandong', 'zhongyuan', 'jingchu', 'lingnan'],
    center: { x: 740, y: 540 },
    polygon: [],
    provinceNames: ['江苏', '上海', '浙江', '福建', '台湾'],
  },
  {
    id: 'lingnan',
    name: '岭南',
    neighbors: ['bashu', 'jingchu', 'jiangdong'],
    center: { x: 528, y: 690 },
    polygon: [],
    provinceNames: ['云南', '广西', '广东', '海南', '香港', '澳门'],
  },
];

export const characters: CharacterConfig[] = [
  { id: 'qin-shihuang', name: '秦始皇', dynasty: '秦', role: 'emperor', leadership: 91, offense: 85, defense: 79, mobility: 75, resilience: 84, strategy: 82, tags: ['统一', '高压'] },
  { id: 'wang-jian', name: '王翦', dynasty: '秦', role: 'general', leadership: 94, offense: 90, defense: 88, mobility: 73, resilience: 86, strategy: 81, tags: ['稳健'] },
  { id: 'liu-bang', name: '刘邦', dynasty: '汉', role: 'emperor', leadership: 84, offense: 78, defense: 75, mobility: 77, resilience: 92, strategy: 86, tags: ['韧性'] },
  { id: 'han-xin', name: '韩信', dynasty: '汉', role: 'general', leadership: 97, offense: 96, defense: 83, mobility: 90, resilience: 77, strategy: 93, tags: ['奇兵'] },
  { id: 'cao-cao', name: '曹操', dynasty: '魏', role: 'emperor', leadership: 92, offense: 88, defense: 81, mobility: 87, resilience: 83, strategy: 92, tags: ['机变'] },
  { id: 'zhang-liao', name: '张辽', dynasty: '魏', role: 'general', leadership: 89, offense: 88, defense: 80, mobility: 84, resilience: 79, strategy: 76, tags: ['突击'] },
  { id: 'li-shimin', name: '李世民', dynasty: '唐', role: 'emperor', leadership: 97, offense: 94, defense: 88, mobility: 90, resilience: 90, strategy: 91, tags: ['全能'] },
  { id: 'li-jing', name: '李靖', dynasty: '唐', role: 'general', leadership: 95, offense: 93, defense: 87, mobility: 90, resilience: 82, strategy: 89, tags: ['远征'] },
  { id: 'zhao-kuangyin', name: '赵匡胤', dynasty: '宋', role: 'emperor', leadership: 87, offense: 79, defense: 85, mobility: 72, resilience: 88, strategy: 84, tags: ['稳盘'] },
  { id: 'yue-fei', name: '岳飞', dynasty: '宋', role: 'general', leadership: 94, offense: 90, defense: 91, mobility: 80, resilience: 90, strategy: 84, tags: ['坚守'] },
  { id: 'chengjisihan', name: '成吉思汗', dynasty: '元', role: 'emperor', leadership: 96, offense: 98, defense: 78, mobility: 98, resilience: 84, strategy: 85, tags: ['疾袭'] },
  { id: 'muhuali', name: '木华黎', dynasty: '元', role: 'general', leadership: 90, offense: 91, defense: 75, mobility: 94, resilience: 80, strategy: 82, tags: ['追击'] },
  { id: 'zhu-yuanzhang', name: '朱元璋', dynasty: '明', role: 'emperor', leadership: 93, offense: 85, defense: 89, mobility: 80, resilience: 92, strategy: 88, tags: ['运营'] },
  { id: 'xu-da', name: '徐达', dynasty: '明', role: 'general', leadership: 91, offense: 89, defense: 87, mobility: 83, resilience: 86, strategy: 84, tags: ['推进'] },
  { id: 'kangxi', name: '康熙', dynasty: '清', role: 'emperor', leadership: 90, offense: 82, defense: 88, mobility: 78, resilience: 89, strategy: 90, tags: ['平衡'] },
  { id: 'duoergun', name: '多尔衮', dynasty: '清', role: 'royal', leadership: 88, offense: 86, defense: 83, mobility: 84, resilience: 82, strategy: 81, tags: ['接管'] },
];

export const factionTemplates: FactionTemplate[] = [
  { id: 'qin', name: '大秦', dynasty: '秦', color: '#c95f42', characterIds: ['qin-shihuang', 'wang-jian'], startRegionId: 'guanzhong' },
  { id: 'han', name: '大汉', dynasty: '汉', color: '#c6a247', characterIds: ['liu-bang', 'han-xin'], startRegionId: 'zhongyuan' },
  { id: 'wei', name: '曹魏', dynasty: '魏', color: '#5978c7', characterIds: ['cao-cao', 'zhang-liao'], startRegionId: 'hebei' },
  { id: 'tang', name: '大唐', dynasty: '唐', color: '#3f9b72', characterIds: ['li-shimin', 'li-jing'], startRegionId: 'shandong' },
  { id: 'song', name: '大宋', dynasty: '宋', color: '#8267bb', characterIds: ['zhao-kuangyin', 'yue-fei'], startRegionId: 'jiangdong' },
  { id: 'yuan', name: '大元', dynasty: '元', color: '#7f8a3d', characterIds: ['chengjisihan', 'muhuali'], startRegionId: 'mobei' },
  { id: 'ming', name: '大明', dynasty: '明', color: '#d04b78', characterIds: ['zhu-yuanzhang', 'xu-da'], startRegionId: 'jingchu' },
  { id: 'qing', name: '大清', dynasty: '清', color: '#4e8f9b', characterIds: ['kangxi', 'duoergun'], startRegionId: 'liaodong' },
];
